import Foundation

/// Pool of 200 greeting lines shown beneath the wordmark on the Library
/// home header. Selection is handled by `GreetingPicker`.
///
/// Updated for redesign — emoji removed per spec. Six lines previously
/// carried a single emoji each (☕ × 2, 🌙 × 2, 📓, 🍷); each was rewritten
/// in place so the tag distribution remains identical.
///
/// Tag values: `morning`, `afternoon`, `evening`, `latenight`,
/// `monday`...`sunday`, or `nil` for evergreen.
///
/// Distribution:
///   morning    30
///   afternoon  20
///   evening    25
///   latenight  15
///   per-day     5  (× 7 = 35)
///   evergreen  75
///   ─────────────
///   total     200
let greetings: [(text: String, tag: String?)] = [

    // MARK: - Morning (30)
    (text: "good morning. coffee first?", tag: "morning"),
    (text: "the day's still soft. ease in.", tag: "morning"),
    (text: "what's the first thought?", tag: "morning"),
    (text: "morning brain is honest brain.", tag: "morning"),
    (text: "before email, before everything — write.", tag: "morning"),
    (text: "early. quiet. yours.", tag: "morning"),
    (text: "the page is awake before you are.", tag: "morning"),
    (text: "still half-asleep. that's fine.", tag: "morning"),
    (text: "first thoughts tend to be the truest.", tag: "morning"),
    (text: "morning. what's worth keeping?", tag: "morning"),
    (text: "the world hasn't reached you yet.", tag: "morning"),
    (text: "ten minutes before the noise starts.", tag: "morning"),
    (text: "morning. one thought at a time.", tag: "morning"),
    (text: "what did you sleep on?", tag: "morning"),
    (text: "soft start. no pressure.", tag: "morning"),
    (text: "morning light, blank page.", tag: "morning"),
    (text: "before the day claims you.", tag: "morning"),
    (text: "what's louder than the kettle?", tag: "morning"),
    (text: "the dream's still here. write it down.", tag: "morning"),
    (text: "small thoughts now, big ones later.", tag: "morning"),
    (text: "morning. mind on warm-up.", tag: "morning"),
    (text: "the sun's up. the page is up.", tag: "morning"),
    (text: "what you remember from last night counts.", tag: "morning"),
    (text: "yesterday's mess, today's clarity.", tag: "morning"),
    (text: "morning is a kind editor.", tag: "morning"),
    (text: "no notifications yet. enjoy it.", tag: "morning"),
    (text: "what would today regret you not writing?", tag: "morning"),
    (text: "the cursor's been waiting.", tag: "morning"),
    (text: "early thoughts age well.", tag: "morning"),
    (text: "good morning. begin gently.", tag: "morning"),

    // MARK: - Afternoon (20)
    (text: "second coffee, second wind.", tag: "afternoon"),
    (text: "afternoon dip. ride it out.", tag: "afternoon"),
    (text: "the morning's notes need a re-read.", tag: "afternoon"),
    (text: "midday. mid-thought.", tag: "afternoon"),
    (text: "what survived the morning?", tag: "afternoon"),
    (text: "afternoon brain wants something simple.", tag: "afternoon"),
    (text: "you've earned a slower paragraph.", tag: "afternoon"),
    (text: "lunch was a long time ago.", tag: "afternoon"),
    (text: "the day's at its hinge.", tag: "afternoon"),
    (text: "second half. less performative.", tag: "afternoon"),
    (text: "afternoon. fewer ideas, better ones.", tag: "afternoon"),
    (text: "the 3pm thought is usually the real one.", tag: "afternoon"),
    (text: "still here. that counts.", tag: "afternoon"),
    (text: "what's the afternoon trying to tell you?", tag: "afternoon"),
    (text: "warm light, slower pace.", tag: "afternoon"),
    (text: "halfway through. how's it going?", tag: "afternoon"),
    (text: "afternoon writes itself differently.", tag: "afternoon"),
    (text: "the morning's optimism has cooled. good.", tag: "afternoon"),
    (text: "less caffeine, more honesty.", tag: "afternoon"),
    (text: "afternoon. you've still got time.", tag: "afternoon"),

    // MARK: - Evening (25)
    (text: "evening. wind it down.", tag: "evening"),
    (text: "what's worth keeping from today?", tag: "evening"),
    (text: "the day's nearly closed. capture it.", tag: "evening"),
    (text: "evening light is forgiving.", tag: "evening"),
    (text: "tomorrow can wait. tonight, write.", tag: "evening"),
    (text: "what did today actually mean?", tag: "evening"),
    (text: "evening notes are usually wiser.", tag: "evening"),
    (text: "the sun's leaving. the page isn't.", tag: "evening"),
    (text: "small reckonings, while it's quiet.", tag: "evening"),
    (text: "evening. honest hour.", tag: "evening"),
    (text: "today, in three sentences.", tag: "evening"),
    (text: "what did you almost forget?", tag: "evening"),
    (text: "the day looks different from here.", tag: "evening"),
    (text: "evening. settle in.", tag: "evening"),
    (text: "before bed, one good thought.", tag: "evening"),
    (text: "what's the evening version of this?", tag: "evening"),
    (text: "today's nearly archived. annotate it.", tag: "evening"),
    (text: "the long shadows tell better stories.", tag: "evening"),
    (text: "evening invites the truer line.", tag: "evening"),
    (text: "what mattered, when you stop pretending?", tag: "evening"),
    (text: "soft hour. soft thoughts.", tag: "evening"),
    (text: "the day deserves a footnote.", tag: "evening"),
    (text: "evening. less editing, more noticing.", tag: "evening"),
    (text: "what stays after the day goes?", tag: "evening"),
    (text: "tonight's notes are tomorrow's clarity.", tag: "evening"),

    // MARK: - Late night (15)
    (text: "midnight thoughts age poorly. write anyway.", tag: "latenight"),
    (text: "you should be asleep. but here we are.", tag: "latenight"),
    (text: "the late page is the honest page.", tag: "latenight"),
    (text: "1am. brave or unwise. probably both.", tag: "latenight"),
    (text: "everyone else is dreaming. you're drafting.", tag: "latenight"),
    (text: "this thought waited until now for a reason.", tag: "latenight"),
    (text: "latenight clarity is mostly fiction.", tag: "latenight"),
    (text: "the cursor is the only witness.", tag: "latenight"),
    (text: "tomorrow you'll thank or delete this.", tag: "latenight"),
    (text: "quiet world. loud mind.", tag: "latenight"),
    (text: "late. but not too late.", tag: "latenight"),
    (text: "the small hours tell on you.", tag: "latenight"),
    (text: "write it. then sleep.", tag: "latenight"),
    (text: "3am. be kind to yourself.", tag: "latenight"),
    (text: "future you can edit this.", tag: "latenight"),

    // MARK: - Monday (5)
    (text: "monday again. apologies.", tag: "monday"),
    (text: "monday brain. low expectations.", tag: "monday"),
    (text: "the week is waiting. so is the page.", tag: "monday"),
    (text: "monday. start with the smallest thing.", tag: "monday"),
    (text: "fresh week. blank slate. unrealistic, but try.", tag: "monday"),

    // MARK: - Tuesday (5)
    (text: "tuesday. underrated.", tag: "tuesday"),
    (text: "tuesday is for actually doing it.", tag: "tuesday"),
    (text: "the quiet middle of the early week.", tag: "tuesday"),
    (text: "tuesday. head down.", tag: "tuesday"),
    (text: "tuesday has nothing to prove.", tag: "tuesday"),

    // MARK: - Wednesday (5)
    (text: "wednesday. mid-week reckoning.", tag: "wednesday"),
    (text: "the hump. write through it.", tag: "wednesday"),
    (text: "wednesday is honest. lean in.", tag: "wednesday"),
    (text: "halfway. how's the week treating you?", tag: "wednesday"),
    (text: "wednesday wants a small win.", tag: "wednesday"),

    // MARK: - Thursday (5)
    (text: "thursday. friday in disguise.", tag: "thursday"),
    (text: "thursday's thoughts feel almost free.", tag: "thursday"),
    (text: "nearly there. keep going.", tag: "thursday"),
    (text: "thursday. the week's been strange.", tag: "thursday"),
    (text: "thursday is for tying up loose threads.", tag: "thursday"),

    // MARK: - Friday (5)
    (text: "friday brain. embrace it.", tag: "friday"),
    (text: "friday. the page is loosening.", tag: "friday"),
    (text: "you made it. one more page.", tag: "friday"),
    (text: "friday. lighter thoughts allowed.", tag: "friday"),
    (text: "friday writes itself in shorter sentences.", tag: "friday"),

    // MARK: - Saturday (5)
    (text: "saturday. no agenda.", tag: "saturday"),
    (text: "saturday is for the slower thought.", tag: "saturday"),
    (text: "weekend mind. let it wander.", tag: "saturday"),
    (text: "saturday. write without a reason.", tag: "saturday"),
    (text: "saturday morning is its own genre.", tag: "saturday"),

    // MARK: - Sunday (5)
    (text: "sunday reset. gently.", tag: "sunday"),
    (text: "sunday. plan, or don't.", tag: "sunday"),
    (text: "the week ahead can wait an hour.", tag: "sunday"),
    (text: "sunday is for the quieter draft.", tag: "sunday"),
    (text: "sunday. think long, write short.", tag: "sunday"),

    // MARK: - Evergreen (75)
    (text: "what's on your mind?", tag: nil),
    (text: "the page is patient. it'll wait.", tag: nil),
    (text: "one sentence is enough.", tag: nil),
    (text: "start anywhere. the order will sort itself.", tag: nil),
    (text: "say it badly first.", tag: nil),
    (text: "the blank page is not the enemy.", tag: nil),
    (text: "what if no one read this?", tag: nil),
    (text: "small notes compound.", tag: nil),
    (text: "draft it ugly.", tag: nil),
    (text: "the cursor doesn't judge.", tag: nil),
    (text: "you don't owe this page anything tidy.", tag: nil),
    (text: "where were we?", tag: nil),
    (text: "what changed since the last entry?", tag: nil),
    (text: "the unwritten thought is the loudest.", tag: nil),
    (text: "begin in the middle.", tag: nil),
    (text: "no one else has to see this.", tag: nil),
    (text: "what's the truest sentence you've got?", tag: nil),
    (text: "the page keeps your secrets.", tag: nil),
    (text: "one paragraph, then close it.", tag: nil),
    (text: "what are you avoiding writing?", tag: nil),
    (text: "say less. mean more.", tag: nil),
    (text: "the obvious thing is usually the right thing.", tag: nil),
    (text: "if you don't write it, who will?", tag: nil),
    (text: "what's the smaller version of that thought?", tag: nil),
    (text: "the boring detail is often the gold.", tag: nil),
    (text: "what would you write with nothing to lose?", tag: nil),
    (text: "again. but better this time.", tag: nil),
    (text: "you've got time for one more line.", tag: nil),
    (text: "stop performing. just write.", tag: nil),
    (text: "what do you actually think?", tag: nil),
    (text: "the half-formed idea still counts.", tag: nil),
    (text: "press on.", tag: nil),
    (text: "messy now, clean later.", tag: nil),
    (text: "the question is usually better than the answer.", tag: nil),
    (text: "leave a thread for tomorrow you.", tag: nil),
    (text: "what's nagging at you?", tag: nil),
    (text: "note it before it leaves.", tag: nil),
    (text: "what was the original feeling?", tag: nil),
    (text: "you can always cross it out.", tag: nil),
    (text: "shorter than you think it should be.", tag: nil),
    (text: "what's the headline?", tag: nil),
    (text: "if it scares you to write, write it.", tag: nil),
    (text: "trust the first phrasing.", tag: nil),
    (text: "you don't need a thesis. just a thought.", tag: nil),
    (text: "what's the thing under the thing?", tag: nil),
    (text: "the page won't tell anyone.", tag: nil),
    (text: "no preamble. straight in.", tag: nil),
    (text: "what's been on repeat in your head?", tag: nil),
    (text: "say the part you keep skipping.", tag: nil),
    (text: "every notebook starts incomplete.", tag: nil),
    (text: "leave space for revision.", tag: nil),
    (text: "what would older you write here?", tag: nil),
    (text: "and younger you?", tag: nil),
    (text: "imperfect and finished beats perfect and never.", tag: nil),
    (text: "you came back. that matters.", tag: nil),
    (text: "the page noticed.", tag: nil),
    (text: "where did the thought go?", tag: nil),
    (text: "catch it before it drifts.", tag: nil),
    (text: "less curating. more capturing.", tag: nil),
    (text: "be specific. specifics survive.", tag: nil),
    (text: "what's true in just this moment?", tag: nil),
    (text: "the small observation, please.", tag: nil),
    (text: "no one writes well on the first try.", tag: nil),
    (text: "okay. what now?", tag: nil),
    (text: "the page is on your side.", tag: nil),
    (text: "what's the next sentence?", tag: nil),
    (text: "you don't need to know where it's going.", tag: nil),
    (text: "leave it open. close it tomorrow.", tag: nil),
    (text: "name the feeling first.", tag: nil),
    (text: "the loose thought, before it tightens.", tag: nil),
    (text: "the journal is the only fair witness.", tag: nil),
    (text: "what's worth remembering in a year?", tag: nil),
    (text: "give it a single line. that's enough.", tag: nil),
    (text: "what would you say if asked, honestly?", tag: nil),
    (text: "begin. begin again. that's the whole trick.", tag: nil),
]
