import Foundation

/// On-device caches for AI-generated artefacts. Three kinds:
///   • Summaries — UserDefaults dictionary keyed by notebook UUID,
///     value is `{ text: String, generatedFor: Date }` so a stale
///     entry can be detected when the notebook's `updatedAt` moves
///     past `generatedFor`.
///   • Tag-suggestion-dismissed flags — UserDefaults set of UUIDs.
///     Once a user dismisses the suggested-tags banner for a
///     notebook, it never reappears for that notebook.
///   • Embeddings — binary `[Float]` arrays in
///     `Documents/embeddings/<uuid>.bin`. Generated by Phase 4's
///     semantic-search pipeline; purged when a notebook is
///     reaper-deleted.
///
/// All file-system writes happen on the calling actor; the format
/// is tiny (one float vector per notebook, ~2KB at 512 dims) so
/// there's no async pressure here.
enum IntelligenceCache {

    // MARK: - Summaries

    private struct SummaryEntry: Codable {
        let text: String
        let generatedFor: Date
    }

    private static let summaryKey = "intelligence.summaries.v1"

    /// Returns the cached summary for the notebook iff one exists
    /// AND `notebookUpdatedAt <= entry.generatedFor` (i.e. the
    /// notebook hasn't been edited since the summary was made).
    /// Returns nil for stale entries — the caller re-generates.
    static func summary(
        for notebookId: UUID,
        notebookUpdatedAt: Date,
        defaults: UserDefaults = .standard
    ) -> String? {
        guard let entry = readSummaryMap(defaults: defaults)[notebookId.uuidString]
        else { return nil }
        guard notebookUpdatedAt <= entry.generatedFor else { return nil }
        return entry.text
    }

    static func setSummary(
        _ text: String,
        for notebookId: UUID,
        generatedFor: Date = Date(),
        defaults: UserDefaults = .standard
    ) {
        var map = readSummaryMap(defaults: defaults)
        map[notebookId.uuidString] = SummaryEntry(
            text: text,
            generatedFor: generatedFor
        )
        writeSummaryMap(map, defaults: defaults)
    }

    static func clearSummaries(
        for notebookIds: [UUID],
        defaults: UserDefaults = .standard
    ) {
        guard !notebookIds.isEmpty else { return }
        var map = readSummaryMap(defaults: defaults)
        for id in notebookIds { map.removeValue(forKey: id.uuidString) }
        writeSummaryMap(map, defaults: defaults)
    }

    private static func readSummaryMap(
        defaults: UserDefaults
    ) -> [String: SummaryEntry] {
        guard let raw  = defaults.string(forKey: summaryKey),
              let data = raw.data(using: .utf8),
              let map  = try? JSONDecoder().decode(
                  [String: SummaryEntry].self, from: data
              )
        else { return [:] }
        return map
    }

    private static func writeSummaryMap(
        _ map: [String: SummaryEntry],
        defaults: UserDefaults
    ) {
        if map.isEmpty {
            defaults.removeObject(forKey: summaryKey)
            return
        }
        guard let data = try? JSONEncoder().encode(map),
              let str  = String(data: data, encoding: .utf8)
        else { return }
        defaults.set(str, forKey: summaryKey)
    }

    // MARK: - Suggested-tags dismiss flag

    /// `true` when the user has dismissed the suggested-tags banner
    /// for `notebookId`. Set once, persisted forever — the banner
    /// never reappears for that notebook even if its content changes.
    static func tagsDismissed(
        for notebookId: UUID,
        defaults: UserDefaults = .standard
    ) -> Bool {
        let set = readDismissedSet(defaults: defaults)
        return set.contains(notebookId.uuidString)
    }

    static func markTagsDismissed(
        for notebookId: UUID,
        defaults: UserDefaults = .standard
    ) {
        var set = readDismissedSet(defaults: defaults)
        set.insert(notebookId.uuidString)
        writeDismissedSet(set, defaults: defaults)
    }

    static func clearDismissedTags(
        for notebookIds: [UUID],
        defaults: UserDefaults = .standard
    ) {
        guard !notebookIds.isEmpty else { return }
        var set = readDismissedSet(defaults: defaults)
        for id in notebookIds { set.remove(id.uuidString) }
        writeDismissedSet(set, defaults: defaults)
    }

    private static let dismissedKey = "intelligence.tagsDismissed.v1"

    private static func readDismissedSet(defaults: UserDefaults) -> Set<String> {
        Set(defaults.stringArray(forKey: dismissedKey) ?? [])
    }

    private static func writeDismissedSet(_ set: Set<String>, defaults: UserDefaults) {
        if set.isEmpty {
            defaults.removeObject(forKey: dismissedKey)
            return
        }
        defaults.set(Array(set), forKey: dismissedKey)
    }

    // MARK: - Embeddings

    private static var embeddingsDir: URL {
        let docs = FileManager.default
            .urls(for: .documentDirectory, in: .userDomainMask)[0]
        return docs.appendingPathComponent("embeddings", isDirectory: true)
    }

    private static func embeddingURL(for notebookId: UUID) -> URL {
        embeddingsDir.appendingPathComponent("\(notebookId.uuidString).bin")
    }

    /// Read the embedding vector for a notebook, if one's been
    /// generated. Returns nil on missing file / parse failure.
    static func embedding(for notebookId: UUID) -> [Float]? {
        let url = embeddingURL(for: notebookId)
        guard let data = try? Data(contentsOf: url) else { return nil }
        let count = data.count / MemoryLayout<Float>.size
        guard count > 0 else { return nil }
        return data.withUnsafeBytes { raw -> [Float] in
            let buf = raw.bindMemory(to: Float.self)
            return Array(UnsafeBufferPointer(start: buf.baseAddress, count: count))
        }
    }

    static func setEmbedding(
        _ vector: [Float],
        for notebookId: UUID
    ) {
        try? FileManager.default.createDirectory(
            at: embeddingsDir,
            withIntermediateDirectories: true
        )
        let url = embeddingURL(for: notebookId)
        let data = vector.withUnsafeBufferPointer {
            Data(buffer: $0)
        }
        try? data.write(to: url, options: .atomic)
    }

    static func clearEmbeddings(for notebookIds: [UUID]) {
        for id in notebookIds {
            try? FileManager.default.removeItem(at: embeddingURL(for: id))
        }
    }
}
